<?php
/**
 * 全局错误代码类ss
 */
namespace Common\Lib;
define("BASE_SYSTEM",1);//系统级错误
define("BASE_CLIENT",2);//应用级错误
class BaseErrorCode{
    const PARAM_ERROR = BASE_SYSTEM . 10000;
    const DEVICR_TYPE_ERROR = BASE_SYSTEM . 10001;
    const PHONENUMBER_ERROR = BASE_SYSTEM . 10002;
    const OPERATION_ERROR = BASE_SYSTEM . 10003;
    const PLEASE_LOGIN = BASE_SYSTEM . 10004;
    const PROVINCES_AND_MUNICIPALITIES_TO_RECEIVE_THE_ADDRESS_MUST_BE_CONSISTENT_WITH_THE_PROVINCIAL_CERTIFICATION = BASE_SYSTEM . 10005;
    const YOU_ARE_REGISTERED_PLEASE_LOGIN_DIRECTLY = BASE_SYSTEM . 10006;
    const YOU_ARE_NOT_REGISTERED_PLEASE_REG = BASE_SYSTEM . 10007;
    const SALES_CAN_NOT_BE_ON_BEHALF_OF_CUSTOMER_ORDERS = BASE_SYSTEM . 10008;
    const PHONENUMBER_REGISTERED = BASE_SYSTEM . 20001;
    const PHONENUMBER_NOT_VERIFICATION = BASE_SYSTEM . 20002;
    const USER_DOESENT_EXIST = BASE_SYSTEM . 20003;
    const PASSWORD_ERROR = BASE_SYSTEM . 20004;
    const AUTHCODE_ERROR = BASE_SYSTEM . 20005;
    const ADDRESS_ERROR = BASE_SYSTEM . 20006;
    const NICKNAME_HAS_BEEN_REGISTERED = BASE_SYSTEM . 20007;
    const THE_PHONENUMBER_ISENT_REGISTERED_PLEASE_REGISTER = BASE_SYSTEM . 20008;
    const YOU_CANT_SUBMIT_STOREBASIC_DATA_NOW = BASE_SYSTEM . 20009;
    const YOU_CANT_SUBMIT_STOREPERFECT_DATA_NOW = BASE_SYSTEM . 20010;
    const YOU_CANNOT_MODIFY_INVOICE_INFORMATION = BASE_SYSTEM . 20011;
    const INITIAL_STORE_ADDRESS_ISNT_ALLOWED_DELETE = BASE_SYSTEM . 20012;
    const YOU_ARE_NOT_ALLOWED_TO_MODIFY_STATE = BASE_SYSTEM . 20013;
    const INITIAL_STORE_ADDRESS_ARE_NOT_ALLOWED_CHANGE = BASE_SYSTEM . 20014;
    const YOU_HAVE_NOT_YET_SUBMITTED_INVOICE_INFORMATION = BASE_SYSTEM . 20015;
    const SALER_ID_IS_NEEDED = BASE_SYSTEM . 20016;
    const OPTION_FAILED = BASE_SYSTEM . 3000010;
    const GOODS_HAVE_BEEN_ISSUED_CANCEL_FAILED = BASE_SYSTEM . 30001;
    const CANNOT_CANCEL_THE_OTHERS_ORDERS = BASE_SYSTEM . 30002;
    const THE_ORDER_HAS_BEEN_CANCELED_DO_NOT_REPEAT_THE_OPERATION = BASE_SYSTEM . 30003;
    const FAILED_PLEASE_CONTACT_CUSTOMER_SERVICE = BASE_SYSTEM . 30004;
    const FAILURE_TO_CANCEL_ORDERS_PLEASE_CONTACT_CUSTOMER_SERVICE = BASE_SYSTEM . 30005;
    const ORDER_IS_CANCELLED_PLEASE_WAIT = BASE_SYSTEM . 30006;
    const CANNOT_DELETE_OTHERSORDERS = BASE_SYSTEM . 30007;
    const THE_ORDER_HAS_BEEN_DELETED_DO_NOT_REPEAT_THE_OPERATION = BASE_SYSTEM . 30008;
    const CANNOT_DELETE_THE_CURRENT_ORDER = BASE_SYSTEM . 30009;
    const ORDER_DELETE_FAILED = BASE_SYSTEM . 30010;
    const ORDER_HAS_BEEN_SHIPPED_CANNOT_CANCEL_THE_ORDER_OR_REFUND = BASE_SYSTEM . 30011;
    const ORDERS_DID_NOT_PAY_CAN_NOT_REFUND_OPERATION = BASE_SYSTEM . 30012;
    const ORDER_ID_IS_NEEDED = BASE_SYSTEM . 30013;
    const CANNOT_CANCLE_OTHERSORDERS = BASE_SYSTEM . 30014;
    const THE_ORDER_HAS_BEEN_CANCLE_DO_NOT_REPEAT_THE_OPERATION = BASE_SYSTEM . 30015;
    const ORDER_CANCLE_FAILED = BASE_SYSTEM . 30016;
    const WAREHOUSE_PROHBIT_EDIT_ORDER = BASE_SYSTEM . 30017;
    const WAREHOUSE_EDIT_ORDER_FAILED = BASE_SYSTEM . 30018;
    const ORDER_EDIT_FAILED = BASE_SYSTEM . 30019;
    const PLEASE_INPUT_ORDER_FAVOURABLE_AMOUNT = BASE_SYSTEM . 30020;
    const GET_ORDER_DETAIL_FAILED = BASE_SYSTEM . 30021;
    const ORDER_HAS_BE_PAID = BASE_SYSTEM . 30022;
    const ORDER_PRICE_LESS_THAN_FAVOURABLE = BASE_SYSTEM . 30023;
    const ORDER_GOODS_ERROR = BASE_SYSTEM . 30024;
    const ORDER_EXPRESS_ERROR = BASE_SYSTEM . 30025;
    const ORDER_HAS_NO_PAY_PLEASE_ASK_SALER_BOOK_ANOTHER = BASE_SYSTEM . 30026;
    const ORDER_HAS_INCLUDE_COUPON_CANNOT_EDIT =BASE_SYSTEM .  30027;
    const ORDER_HAS_INCLUDE_PRESENT_ACTIVITY_CANNOT_EDIT = BASE_SYSTEM . 30028;
    const ORDER_HAS_INCLUDE_PRESALE_ACTIVITY_CANNOT_EDIT = BASE_SYSTEM . 30029;
    const ORDER_GOODS_NOT_EXIST = BASE_SYSTEM . 30030;
    const ORDER_GOODS_PRICE_ERROR = BASE_SYSTEM . 30031;
    const ORDER_GOODS_NOT_PRESENT_PRICE_CANNOT_BE_ZERO = BASE_SYSTEM . 30032;
    const ORDER_LACK_RECEIVE_MOBILE = BASE_SYSTEM . 30033;
    const ORDER_CANNOT_GET_SALERINFO = BASE_SYSTEM . 30034;
    const ORDER_LACK_RECEIVE_ADDRESS = BASE_SYSTEM . 30035;
    const ORDER_ADDRESS_ERROR = BASE_SYSTEM . 30036;
    const ORDER_LACK_PAY_TYPE = BASE_SYSTEM . 30037;
    const ORDER_SALERINFO_ERROR = BASE_SYSTEM . 30038;
    const ORDER_GOODS_NUM_ERROR = BASE_SYSTEM . 30039;
    const ORDER_PLEASE_ENTER_RIGHTFUL_ORDERID = BASE_SYSTEM . 30040;
    const ORDER_PLEASE_ENTER_OFFLINE_PAY_AMOUNT = BASE_SYSTEM . 30041;
    const ORDER_YOU_ARE_NOT_ALLOW = BASE_SYSTEM . 30042;
    const ORDER_PLEASE_ENTER_OFFLINE_PAY_TYPE = BASE_SYSTEM . 30043;
    const ORDER_OFFLINE_PAY_STATUS_EDIT_FAILED = BASE_SYSTEM . 30044;
    const ORDER_INFO_FIELD_MUST_ARRAY = BASE_SYSTEM . 30045;
    const ORDER_DATA_EMPTY = BASE_SYSTEM . 30046;
    const ORDER_HAS_PAIED_CANNOT_EDIT_PAY_FLOW = BASE_SYSTEM . 30047;
    const ORDER_EDIT_PARAM_EMPTY = BASE_SYSTEM . 30048;
    const ORDER_APY_TYPE_ISNEED = BASE_SYSTEM . 30049;
    const ORDER_GOODS_NUM_CANNOT_LESSTHAN_ZERO = BASE_SYSTEM . 30050;
    const ORDER_GET_EXPRESS_FEE_FAILED = BASE_SYSTEM . 30051;
    const ORDER_GEN_PARAM_ERROR = BASE_SYSTEM . 30052;
    const ORDER_YOUUR_REQUEST_IS_FORBIDDEN = BASE_SYSTEM . 30053;
    const ORDER_STATUS_GET_ERROR = BASE_SYSTEM . 30054;
    const ORDER_INVOICE_TYPE_ERROR = BASE_SYSTEM . 30055;
    const ORDER_RECEIVE_ADDRESS_ERROR = BASE_SYSTEM . 30056;
    const ORDER_GOODS_WAREHOUSE_ERROR = BASE_SYSTEM . 30057;
    const NO_PAY_ORDERS = BASE_SYSTEM . 40001;
    const FILE_UPLOAD_FAILED = BASE_SYSTEM . 50001;
    const YOU_DID_NOT_SUBMIT_ANY_CONTENT = BASE_SYSTEM . 50002;
    const PLEASE_USE_THE_CORRECT_WAY_TO_UPLOAD = BASE_SYSTEM . 50003;
    const FILE_UPLOAD_FAILED_PLEASE_TRY_AGAIN = BASE_SYSTEM . 50004;
    const FORMAT_ALLOWS_THE_FILE_UPLOAD = BASE_SYSTEM . 50005;
    const FILE_SIZE_LIMIT_PLEASE_UPLOAD_PICTURESNO_MORE_THAN_5M = BASE_SYSTEM . 50006;
    const FAILED_DATA_ACQUISITION_OF_GOODS = BASE_SYSTEM . 60000;
    const IS_NOT_ALLOWED_TO_BUY_THE_NUMBER = BASE_SYSTEM . 60001;
    const INVENTORY_SHORTAGE = BASE_SYSTEM . 60002;
//	const IS_NOT_ALLOWED_TO_BUY_THE_NUMBER = 60003;
    const ORDER_AMOUNT_DOES_NOT_MEET_THE_CONDITIONS_OF_PURCHASE = BASE_SYSTEM . 60006;
    const TO_ALLOW_THE_SALE_AREA = BASE_SYSTEM . 60007;
//	const FAILED_DATA_ACQUISITION_OF_GOODS = 60008;
    const IS_NOT_ALLOWED_TO_BUY_GIFTS = BASE_SYSTEM . 60014;
    const MORE_THAN_THE_PURCHASE_AMOUNT = BASE_SYSTEM . 60015;
    const COMMODITY_DOES_NOT_EXIST = BASE_SYSTEM . 70001;
    const NEED_TO_PAY_THE_AMOUNT_OF_0_DO_NOT_NEED_TO_PAY = BASE_SYSTEM . 70002;
    const ORDER_AMOUNT_HAS_EXCEEDED_300_THOUSAND_PLEASE_CONTACT_THE_CUSTOMER_SERVICE_LINE_TRANSFER =BASE_SYSTEM .  70003;
    const ABNORMAL_ORDERS = BASE_SYSTEM . 80001;
    const DID_NOT_REACH_THE_MINIMUM_PRICE_BATCH_IN_ADVANCE = BASE_SYSTEM . 80002;
    const GET_DATA_FAILED_TO_CANCEL_THE_ORDER = BASE_SYSTEM . 80003;
    const PLEASE_REAL_NAME_AUTHENTICATION = BASE_SYSTEM . 90001;
    const RETURNED_GOODS_CANNOT_BE_GREATER_THAN_THE_NUMBER_OF_GOODSORDERS = BASE_SYSTEM . 11001;
    const YOU_HAVE_SUBMITTED_AN_APPLICATION_PLEASE_DO_NOT_SUBMIT = BASE_SYSTEM . 11002;
    const ABNORMAL_RETURN_FOR = BASE_SYSTEM . 11003;
    const CAUSE_PLEASE_FILL_OUT_THE_DETAILS = BASE_SYSTEM . 11004;
    const PLEASE_CONFIRM_RECEIPT = BASE_SYSTEM . 11005;
    const OVER_TIME_NO_REASON_TO_RETURN = BASE_SYSTEM . 11006;
    const YOUR_ORDER_HAS_NOT_BEEN_SIGNED_PLEASE_CONFIRM_RECEIPT_OF_THE_GOODS = BASE_SYSTEM . 11007;
    const YOUR_APPLICATION_IS_NOT_APPROVED = BASE_SYSTEM . 11008;
    const YOU_HAVE_ALREADY_SUBMITTED_THE_APPLICATION = BASE_SYSTEM . 11009;
    const SYSTEM_UPGRADE_AND_MAINTENANCE_PLEASE_TRY_AGAIN_LATER = BASE_SYSTEM . 99999;
    const YOUR_VERSION_HAS_EXPIRED_PLEASE_UPGRADE_TO_THE_LATEST_VERSION = BASE_SYSTEM . 12000;
    const FAILED_TO_RECEIVE_COUPONS = BASE_SYSTEM . 13000;
    const GET_COUPONS_FAILED = BASE_SYSTEM . 13001;
    const REDEMPTION_CODE_CAN_USE_THE = BASE_SYSTEM . 13002;
    const EXCHANGE_CODE_HAS_EXPIRED = BASE_SYSTEM . 13003;
    const CAN_NOT_FIND_THE_CORRESPONDING_DISCOUNT_COUPONS_PLEASE_CHECK_THE_INPUT_AGAIN_AFTER = BASE_SYSTEM . 13004;
    const COUPON_FORMAT_IS_NOT_CORRECT_PLEASE_TRY_AGAIN = BASE_SYSTEM . 13005;
    const EXCHANGE_CODE_HAS_BEEN_USED = BASE_SYSTEM . 13006;
    const NO_COUPON = BASE_SYSTEM . 13007;
//	const PLEASE_LOGIN = 13008;
    const STOCK_HAS_BEEN_BROUGHT_OUT = BASE_SYSTEM . 13009;
    const HAS_RECEIVED_CAN_NOT_BE_REPEATED_FOR = BASE_SYSTEM . 13010;
    const THIS_COUPON_ONLY_USE_ONCE_ONE_MAN = BASE_SYSTEM . 13015;
    const COUPONS_NOT_AVAILABLE = BASE_SYSTEM . 13011;
    const THIS_ORDER_GOODS_CAN_NOT_CONFIRM_RECEIPT_OF_OH = BASE_SYSTEM . 13012;
    const WRONG_INFORMATION_ACTIVITIES_FULL_OF_GIFTS = BASE_SYSTEM . 14000;
    const YOUR_ERROR_PARAMETERSACTIVITIES = BASE_SYSTEM . 14001;
    const INVALID_ACTIVITY_PARAMETER = BASE_SYSTEM . 14002;
    const INVALID_USER_PARAMETER = BASE_SYSTEM . 14003;
    const UNABLE_TO_OBTAIN_INFORMATION = BASE_SYSTEM . 14004;
    const INVALID_COMMODITY_PARAMETER = BASE_SYSTEM . 14005;
    const YOU_DID_NOT_MEET_THE_CONDITIONS_TO_RECEIVE_GIFTS = BASE_SYSTEM . 14006;
    const CAN_NOT_FIND_THE_GOODSACTIVITIES = BASE_SYSTEM . 14007;
    const TO_FIND_GIFTSACTIVITIES = BASE_SYSTEM . 14008;
    const YOU_ARE_ALREADY_RECEIVING_THE_GIFTSACTIVITIES = BASE_SYSTEM . 14009;
    const THE_GIFTS_ARE_OUT_OF_STOCK_PLEASE_CHOOSE_OTHER_GIFTS = BASE_SYSTEM . 14010;
    const YOUR_INVENTORY_SHORTAGE =BASE_SYSTEM .  14011;
    const ACTIVITIES_IN_THE_MAINTENANCE_PLEASE_TRY_AGAIN_LATER = BASE_SYSTEM . 14012;
    const NUMBER_OF_GIFTS_CAN_NOT_BE_EMPTY = BASE_SYSTEM . 14013;
    const COMMODITY_INVENTORY = BASE_SYSTEM . 14014;
    const YOU_DO_NOT_MEET_THE_CONDITIONS_ACTIVITIES_OH = BASE_SYSTEM . 14015;
    const ACTIVITY_ID_IS_NEED = BASE_SYSTEM . 14016;
    const ACTIVITY_IS_ON_CANNOT_EDIT = BASE_SYSTEM . 14017;
    const ACTIVITY_TYPE_ID_ERROR = BASE_SYSTEM . 14018;
    const ACTIVITY_WAREHOUSE_ID_NEED = BASE_SYSTEM . 14019;
    const ACTIVITY_TITLE_ID_NEED = BASE_SYSTEM . 14020;
    const ACTIVITY_BRAND_HAS_IN_ACTIVITY = BASE_SYSTEM . 14021;
    const ACTIVITY_GOODS_HAS_IN_ACTIVITY = BASE_SYSTEM . 14022;
    const ACTIVITY_GOODS_HAS_IN_PRESALE = BASE_SYSTEM . 14023;
    const ACTIVITY_PRESENT_GOODS_PRICE_OR_NUM_CANNOT_EMPTY = BASE_SYSTEM . 14024;
    const ACTIVITY_PRESENT_GOODS_NUM_CANNOT_EMPTY = BASE_SYSTEM . 14025;
    const ACTIVITY_WAREHOUSE_ERROR = BASE_SYSTEM . 14026;
    const ACTIVITY_PRESENT_WAREHOUSE_ERROR = BASE_SYSTEM . 14027;
    const ACTIVITY_BRAND_WAREHOUSE_ERROR = BASE_SYSTEM . 14028;
    const ACTIVITY_UPDATE_ERROR = BASE_SYSTEM . 14029;
    const ACTIVITY_IS_STOP_CANNOT_UPDATE_CACHE = BASE_SYSTEM . 14030;
    const ACTIVITY_ID_ERROR = BASE_SYSTEM . 14031;
    const ACTIVITY_GOODS_IS_NEED = BASE_SYSTEM . 14032;
    const ACTIVITY_PARAM_IS_NEED = BASE_SYSTEM . 14033;
    const ACTIVITY_ADD_ERROR = BASE_SYSTEM . 14034;
    const ACTIVITY_TYPE_NAME_CANNOT_EMPTY = BASE_SYSTEM . 14035;
    const ACTIVITY_TYPE_ATTRIBUTE_CANNOT_EMPTY = BASE_SYSTEM . 14036;
    const ACTIVITY_CONDITION_CANNOT_EMPTY = BASE_SYSTEM . 14037;
    const ACTIVITY_WAREHOUSE_CANNOT_EMPTY = BASE_SYSTEM . 14038;
    const ACTIVITY_TYPE_ID_IS_NEED = BASE_SYSTEM . 14039;
    const ACTIVITU_ADDITION_TIMES_BEYOND_LIMIT = BASE_SYSTEM . 14040;
    const ACTIVITU_ADDITION_PRESENT_CANNOT_MORE_THAN_ONE = BASE_SYSTEM . 14041;
    const ACTIVITY_ADDITION_HIGHER_CONDITION_MUST_BE_SET = BASE_SYSTEM . 14042;
    const ACTIVITY_GOODS_CACHE_UPDATE_ERROR = BASE_SYSTEM . 14043;
    const ACTIVITY_PRESENT_GOODS_CAN_NOT_BE_EMPTY = BASE_SYSTEM . 14044;
    const ACTIVITY_CONDITION_CAN_NOT_BE_EMPTY = BASE_SYSTEM . 14045;
    const ACTIVITY_CONDITION_ADDITION_CAN_NOT_BE_EMPTY = BASE_SYSTEM . 14046;
    const ACTIVITY_ONLY_WHICHIS_TO_BE_START_CAN_BE_DELETE = BASE_SYSTEM . 14047;
    const ACTIVITY_ONLY_WHICHIS_START_CAN_BE_STOP = BASE_SYSTEM . 14048;
    const ACTIVITY_ONLY_WHICHIS_TO_BE_START_CAN_BE_START = BASE_SYSTEM . 14049;
    const ID_USER_OPERATION_FAILED_ERROR = BASE_SYSTEM . 15001;
    const HONGKONG_WAREHOUSE_ORDER_DOES_NOT_SUPPORT_WECHAT_PAYMENT = BASE_SYSTEM . 16001;
    const THE_GOODS_IN_YOUR_VICINITY_HAVE_A_BIG_SELLERS_IN_THE_SALEPLEASE_CHOOSE_OTHER_BRAND_DIFFERENCE_MANAGEMENT = BASE_SYSTEM . 17001;
    const SETTLE_EXPRESS_ID_ERROR = BASE_SYSTEM . 19001;
    const SETTLE_EXPRESS_NAME_ERROR = BASE_SYSTEM . 19002;
    const SETTLE_EXPRESS_ERROR = BASE_SYSTEM . 19003;
    const SETTLE_GOODS_ERROR = BASE_SYSTEM . 19004;
    const SETTLE_PAY_TYPE_ERROR = BASE_SYSTEM . 19005;
    const SETTLE_GOODS_PRICE_ERROR = BASE_SYSTEM . 19006;
    const SETTLE_GOODS_NUM_ERROR = BASE_SYSTEM . 19007;
    const SETTLE_CANNOT_GET_ORDER_GOODS_INFO = BASE_SYSTEM . 19008;
    const CART_GOODS_ID_ERROR = BASE_SYSTEM . 21001;
    const CART_SALER_ID_ERROR = BASE_SYSTEM . 21002;
    const CART_GOODS_ERROR = BASE_SYSTEM . 21003;
    const CART_GODDS_WAREHOUSE_ERROR = BASE_SYSTEM . 21004;
    const CART_PRESENT_GOODS_ID_ERROR = BASE_SYSTEM . 21005;
    const EXPRESS_GOODS_ERROR = BASE_SYSTEM . 22001;
    const EXPRESS_ID_ERROR = BASE_SYSTEM . 22002;
    const EXPRESS_PAYTYPE_ERROR = BASE_SYSTEM . 22003;
    const YOUR_REQUEST_IS_FORBIDDEN = BASE_SYSTEM . 23000;
    const ACTIVITY_GOODS_OFF_ID_ERROR = BASE_SYSTEM . 24001;
    const ACTIVITY_GOODS_OFF_TITLE_CANNOT_BE_EMPTY = BASE_SYSTEM . 24002;
    const ACTIVITY_GOODS_OFF_UNIT_ATTRIBUTE_CANNOT_BE_EMPTY = BASE_SYSTEM . 24003;
    const ACTIVITY_GOODS_OFF_CONDITION_CANNOT_BE_EMPTY = BASE_SYSTEM . 24004;
    const ACTIVITY_GOODS_CONDITION_IN_GOODS_OFF = BASE_SYSTEM . 24005;
    const ACTIVITY_GOODS_OFF_CONDITION_MUST_INCREASE = BASE_SYSTEM . 24006;
    const ACTIVITY_GOODS_OFF_CART_NUM_ERROR = BASE_SYSTEM . 24007;
    const ACTIVITY_GOODS_OFF_CANNOT_IN_MULTI_ACTIVITY = BASE_SYSTEM . 24008;
    const ACTIVITY_GOODS_OFF_BRAND_CANNOT_IN_MULTI_ACTIVITY = BASE_SYSTEM . 24009;
    const ACTIVITY_GOODS_OFF_GOODS_ID_ERROR = BASE_SYSTEM . 24010;
    const ACTIVITY_GOODS_OFF_BRAND_ID_ERROR = BASE_SYSTEM . 24011;
    const ACTIVITY_GOODS_OFF_ONLY_WAITFORSTART_CANNOT_EDIT = BASE_SYSTEM . 24012;
    const ACTIVITY_GOODS_OFF_UPDATE_ERROR = BASE_SYSTEM . 24013;
    const ACTIVITY_GOODS_OFF_ONLY_WHICHIS_TO_BE_START_CAN_BE_DELETE = BASE_SYSTEM . 24014;
    const ACTIVITY_GOODS_OFF_ONLY_WHICHIS_START_CAN_BE_STOP = BASE_SYSTEM . 24015;
    const ACTIVITY_GOODS_OFF_ONLY_WHICHIS_TO_BE_START_CAN_BE_START = BASE_SYSTEM . 24016;
    const ADD_CART_NUM_GT_ONE = BASE_SYSTEM . 39001;
    const REFUND_IS_LOCKED = BASE_SYSTEM . 39002;
    const ORDER_PRE_PRICE_NOT_GREATER_THAN_GOODS_TOTAL_PRICE = BASE_SYSTEM . 600001;
    const INVOICE_DOES_NOT_EXIST =  BASE_SYSTEM . 600002;
    const FAILED_TO_ADD_INVOICE_REQUEST =  BASE_SYSTEM . 600003;
    const DATA_DOES_NOT_EXIST = BASE_SYSTEM . 30000;

    const TOKEN_CHECK_ERROR = BASE_SYSTEM . 1000110;//token验证失败


    private static $errCode =  array(
        '18001' => '未知错误',
        self::PARAM_ERROR => '参数错误',
        self::DEVICR_TYPE_ERROR => '设备类型错误',
        self::PHONENUMBER_ERROR => '手机号码错误',
        self::OPERATION_ERROR => '操作错误',
        self::PLEASE_LOGIN => '请先登录',
        self::PROVINCES_AND_MUNICIPALITIES_TO_RECEIVE_THE_ADDRESS_MUST_BE_CONSISTENT_WITH_THE_PROVINCIAL_CERTIFICATION => '收货地址的省市必须与认证的省市一致',
        self::YOU_ARE_REGISTERED_PLEASE_LOGIN_DIRECTLY => '您已注册，请直接登录',
        self::YOU_ARE_NOT_REGISTERED_PLEASE_REG => '您未注册，请先注册',
        self::SALES_CAN_NOT_BE_ON_BEHALF_OF_CUSTOMER_ORDERS => '销售员暂不能代客户下单',
        self::PHONENUMBER_REGISTERED => '手机号码已被注册',
        self::PHONENUMBER_NOT_VERIFICATION => '手机号码未验证',
        self::USER_DOESENT_EXIST => '用户不存在',
        self::PASSWORD_ERROR => '密码错误',
        self::AUTHCODE_ERROR => '验证码错误',
        self::ADDRESS_ERROR => '地址错误',
        self::NICKNAME_HAS_BEEN_REGISTERED => '昵称已被注册',
        self::THE_PHONENUMBER_ISENT_REGISTERED_PLEASE_REGISTER=> '该手机号码未注册，请先注册',
        self::YOU_CANT_SUBMIT_STOREBASIC_DATA_NOW => '您现在不能提交店铺基础资料',
        self::YOU_CANT_SUBMIT_STOREPERFECT_DATA_NOW => '您现在不能提交店铺完善资料',
        self::YOU_CANNOT_MODIFY_INVOICE_INFORMATION => '您现在不能修改发票信息',
        self::INITIAL_STORE_ADDRESS_ISNT_ALLOWED_DELETE => '初始店铺地址不允许删除',
        self::YOU_ARE_NOT_ALLOWED_TO_MODIFY_STATE => '您的状态修改不被允许',
        self::INITIAL_STORE_ADDRESS_ARE_NOT_ALLOWED_CHANGE => '初始店铺地址不允许修改',
        self::YOU_HAVE_NOT_YET_SUBMITTED_INVOICE_INFORMATION => '您尚未提交发票信息',
        self::SALER_ID_IS_NEEDED => '缺少用户ID',
        self::OPTION_FAILED => '操作失败',
        self::GOODS_HAVE_BEEN_ISSUED_CANCEL_FAILED => '货物已发出，取消失败',
        self::CANNOT_CANCEL_THE_OTHERS_ORDERS => '不能取消别人的订单',
        self::THE_ORDER_HAS_BEEN_CANCELED_DO_NOT_REPEAT_THE_OPERATION => '该订单已取消，不要重复操作',
        self::FAILED_PLEASE_CONTACT_CUSTOMER_SERVICE => '退款失败，请联系客服',
        self::FAILURE_TO_CANCEL_ORDERS_PLEASE_CONTACT_CUSTOMER_SERVICE => '订单取消失败，请联系客服',
        self::ORDER_IS_CANCELLED_PLEASE_WAIT => '订单正在取消中，请稍等',
        self::CANNOT_DELETE_OTHERSORDERS => '不能删除他人订单',
        self::THE_ORDER_HAS_BEEN_DELETED_DO_NOT_REPEAT_THE_OPERATION => '该订单已删除，不要重复操作',
        self::CANNOT_DELETE_THE_CURRENT_ORDER => '当前订单不能删除',
        self::ORDER_DELETE_FAILED => '订单删除失败',
        self::ORDER_HAS_BEEN_SHIPPED_CANNOT_CANCEL_THE_ORDER_OR_REFUND => '订单已经发货，不能取消订单或者退款',
        self::ORDERS_DID_NOT_PAY_CAN_NOT_REFUND_OPERATION => '订单未支付，不能操作退款',
        self::ORDER_ID_IS_NEEDED => '缺少订单ID',
        self::CANNOT_CANCLE_OTHERSORDERS => '不能取消他人订单',
        self::THE_ORDER_HAS_BEEN_CANCLE_DO_NOT_REPEAT_THE_OPERATION => '该订单已取消，不要重复操作',
        self::ORDER_CANCLE_FAILED => '订单取消失败',
        self::WAREHOUSE_PROHBIT_EDIT_ORDER => '仓库不允许订单修改',
        self::WAREHOUSE_EDIT_ORDER_FAILED => '仓库订单修改失败',
        self::ORDER_EDIT_FAILED => '订单修改失败',
        self::PLEASE_INPUT_ORDER_FAVOURABLE_AMOUNT => '请输入正确优惠金额',
        self::GET_ORDER_DETAIL_FAILED => '获取不到订单详情',
        self::ORDER_HAS_BE_PAID => '订单已经支付',
        self::ORDER_PRICE_LESS_THAN_FAVOURABLE => '订单价格低于优惠金额',
        self::ORDER_GOODS_ERROR => '订单商品错误',
        self::ORDER_EXPRESS_ERROR => '订单运费错误',
        self::ORDER_HAS_NO_PAY_PLEASE_ASK_SALER_BOOK_ANOTHER => '订单还未支付,请让客户重新下单',
        self::ORDER_HAS_INCLUDE_COUPON_CANNOT_EDIT => '订单包含优惠券,不能改单',
        self::ORDER_HAS_INCLUDE_PRESENT_ACTIVITY_CANNOT_EDIT => '订单参与满赠活动,不能改单',
        self::ORDER_HAS_INCLUDE_PRESALE_ACTIVITY_CANNOT_EDIT => '订单参与预售活动,不能改单',
        self::ORDER_GOODS_NOT_EXIST => '该商品不存在或者已经下架',
        self::ORDER_GOODS_PRICE_ERROR => '订单商品价格错误',
        self::ORDER_GOODS_NOT_PRESENT_PRICE_CANNOT_BE_ZERO  => '非赠品商品价格不能为0',
        self::ORDER_LACK_RECEIVE_MOBILE => '缺少收货人手机号',
        self::ORDER_CANNOT_GET_SALERINFO => '获取不到下单人用户信息',
        self::ORDER_LACK_RECEIVE_ADDRESS => '缺少收货人地址信息',
        self::ORDER_ADDRESS_ERROR => '收货地址错误',
        self::ORDER_LACK_PAY_TYPE => '缺少支付类型',
        self::ORDER_SALERINFO_ERROR => '订单用户信息错误',
        self::ORDER_GOODS_NUM_ERROR => '订单商品数量错误',
        self::ORDER_PLEASE_ENTER_RIGHTFUL_ORDERID => '请输入合法的订单ID',
        self::ORDER_PLEASE_ENTER_OFFLINE_PAY_AMOUNT => '请输入线下支付金额',
        self::ORDER_YOU_ARE_NOT_ALLOW => '您没有线下支付确认权限',
        self::ORDER_PLEASE_ENTER_OFFLINE_PAY_TYPE => '请出入线下支付支付类型',
        self::ORDER_OFFLINE_PAY_STATUS_EDIT_FAILED => '订单线下支付状态修改失败',
        self::ORDER_INFO_FIELD_MUST_ARRAY => '订单详情参数必须为数组',
        self::ORDER_DATA_EMPTY => '订单数据为空',
        self::ORDER_HAS_PAIED_CANNOT_EDIT_PAY_FLOW  => '订单已支付,不能再次添加流水',
        self::ORDER_EDIT_PARAM_EMPTY => '订单修改参数为空',
        self::ORDER_APY_TYPE_ISNEED => '订单未选择支付类型',
        self::ORDER_GOODS_NUM_CANNOT_LESSTHAN_ZERO => '订单商品数量不能为0',
        self::ORDER_GET_EXPRESS_FEE_FAILED => '获取运费信息失败',
        self::ORDER_GEN_PARAM_ERROR => '您提交的参数错误',
        self::ORDER_YOUUR_REQUEST_IS_FORBIDDEN => '您的请求不被允许',
        self::ORDER_STATUS_GET_ERROR => '获取订单状态错误',
        self::ORDER_INVOICE_TYPE_ERROR => '订单发票类型错误',
        self::ORDER_RECEIVE_ADDRESS_ERROR => '获取不到订单收货地址',
        self::ORDER_GOODS_WAREHOUSE_ERROR => '订单商品仓库错误',
        self::NO_PAY_ORDERS => '暂时没有可支付订单',
        self::FILE_UPLOAD_FAILED => '文件上传失败',
        self::YOU_DID_NOT_SUBMIT_ANY_CONTENT => '您未提交任何内容',
        self::PLEASE_USE_THE_CORRECT_WAY_TO_UPLOAD => '请您使用正确方式上传',
        self::FILE_UPLOAD_FAILED_PLEASE_TRY_AGAIN => '文件上传失败,请重新尝试',
        self::FORMAT_ALLOWS_THE_FILE_UPLOAD => '非允许文件上传格式',
        self::FILE_SIZE_LIMIT_PLEASE_UPLOAD_PICTURESNO_MORE_THAN_5M => '文件大小超出限制,请上传不超过5M的图片',
        self::FAILED_DATA_ACQUISITION_OF_GOODS => '获取商品数据失败',
        self::IS_NOT_ALLOWED_TO_BUY_THE_NUMBER => '非允许购买数量',
        self::INVENTORY_SHORTAGE => '商品库存不足',
        self::ORDER_PRE_PRICE_NOT_GREATER_THAN_GOODS_TOTAL_PRICE => '优惠价格不能大于商品总价',
        self::IS_NOT_ALLOWED_TO_BUY_THE_NUMBER => '非允许购买数量',
//	    '60004' => '非允许购买数量',
//	    '60005' => '非允许购买数量',
        self::ORDER_AMOUNT_DOES_NOT_MEET_THE_CONDITIONS_OF_PURCHASE  => '订单金额不满足购买条件',
        self::TO_ALLOW_THE_SALE_AREA  => '非允许销售地区',
//	    '60008' => '获取商品数据失败',
//	    '60009' => '获取商品数据失败',
//	    '600010' => '获取商品数据失败',
//	    '600011' => '获取商品数据失败',
//	    '600012' => '获取商品数据失败',
//	    '600013' => '获取商品数据失败',
        self::IS_NOT_ALLOWED_TO_BUY_GIFTS => '赠品不允许购买',
        self::MORE_THAN_THE_PURCHASE_AMOUNT => '超过限购数量',
        self::COMMODITY_DOES_NOT_EXIST => '商品不存在',
        self::NEED_TO_PAY_THE_AMOUNT_OF_0_DO_NOT_NEED_TO_PAY =>  '需要支付的金额为0，不需要再支付',
        self::ORDER_AMOUNT_HAS_EXCEEDED_300_THOUSAND_PLEASE_CONTACT_THE_CUSTOMER_SERVICE_LINE_TRANSFER =>  '订单金额已经超过30万，请联系客服线下转账',
        self::ABNORMAL_ORDERS => '订单异常',
        self::DID_NOT_REACH_THE_MINIMUM_PRICE_BATCH_IN_ADVANCE  =>  '没达到预收批次最低起批价',
        self::GET_DATA_FAILED_TO_CANCEL_THE_ORDER  => '获取取消订单数据失败',
        self::PLEASE_REAL_NAME_AUTHENTICATION  => '请先实名认证',
        self::RETURNED_GOODS_CANNOT_BE_GREATER_THAN_THE_NUMBER_OF_GOODSORDERS  => '退换商品数量不能大于订单商品数量',
        self::YOU_HAVE_SUBMITTED_AN_APPLICATION_PLEASE_DO_NOT_SUBMIT  => '您已经提交过申请,请勿重复提交',
        self::ABNORMAL_RETURN_FOR  => '异常退换货申请',
        self::CAUSE_PLEASE_FILL_OUT_THE_DETAILS  => '请填写详细原因',
        self::PLEASE_CONFIRM_RECEIPT  => '请先确认收货',
        self::OVER_TIME_NO_REASON_TO_RETURN => '已经超过无理由退换货时间',
        self::YOUR_ORDER_HAS_NOT_BEEN_SIGNED_PLEASE_CONFIRM_RECEIPT_OF_THE_GOODS  => '您的订单还未签收，请确认已收到货物',
        self::YOUR_APPLICATION_IS_NOT_APPROVED => '您的申请还未通过审核',
        self::YOU_HAVE_ALREADY_SUBMITTED_THE_APPLICATION => '您已经提交过申请',
        self::SYSTEM_UPGRADE_AND_MAINTENANCE_PLEASE_TRY_AGAIN_LATER => '系统升级维护中,请稍后再试！',
        self::YOUR_VERSION_HAS_EXPIRED_PLEASE_UPGRADE_TO_THE_LATEST_VERSION => '您的版本已过期，请升级最新版本',
        self::FAILED_TO_RECEIVE_COUPONS => '优惠劵领取失败',
        self::GET_COUPONS_FAILED => '获取优惠劵失败',
        self::REDEMPTION_CODE_CAN_USE_THE => '兑换码可以使用',
        self::EXCHANGE_CODE_HAS_EXPIRED => '兑换码已失效',
        self::CAN_NOT_FIND_THE_CORRESPONDING_DISCOUNT_COUPONS_PLEASE_CHECK_THE_INPUT_AGAIN_AFTER => '找不到对应的优惠劵，请核实后重新输入',
        self::COUPON_FORMAT_IS_NOT_CORRECT_PLEASE_TRY_AGAIN => '优惠劵格式不正确，请重试',
        self::EXCHANGE_CODE_HAS_BEEN_USED => '兑换码已被使用',
        self::NO_COUPON => '暂无优惠劵',
        self::PLEASE_LOGIN => '请先登录！',
        self::STOCK_HAS_BEEN_BROUGHT_OUT => '劵已被领完',
        self::HAS_RECEIVED_CAN_NOT_BE_REPEATED_FOR => '已领取，不能重复领取',
        self::THIS_COUPON_ONLY_USE_ONCE_ONE_MAN => '该类优惠劵一个用户只能领取和使用一次',
        self::COUPONS_NOT_AVAILABLE => '优惠劵不可用',
        self::THIS_ORDER_GOODS_CAN_NOT_CONFIRM_RECEIPT_OF_OH => '此订单未发货，不能确认收货哦',
        self::WRONG_INFORMATION_ACTIVITIES_FULL_OF_GIFTS => '满赠活动信息错误',
        self::YOUR_ERROR_PARAMETERSACTIVITIES => '您的活动参数有误',
        self::INVALID_ACTIVITY_PARAMETER => '您的活动参数无效',
        self::INVALID_USER_PARAMETER => '您的用户参数无效',
        self::UNABLE_TO_OBTAIN_INFORMATION => '无法获取活动信息',
        self::INVALID_COMMODITY_PARAMETER => '您的商品参数无效',
        self::YOU_DID_NOT_MEET_THE_CONDITIONS_TO_RECEIVE_GIFTS => '您还未满足赠品领取条件',
        self::CAN_NOT_FIND_THE_GOODSACTIVITIES => '找不到活动商品',
        self::TO_FIND_GIFTSACTIVITIES => '找不到活动赠品',
        self::YOU_ARE_ALREADY_RECEIVING_THE_GIFTSACTIVITIES => '您已经领取过该活动赠品',
        self::THE_GIFTS_ARE_OUT_OF_STOCK_PLEASE_CHOOSE_OTHER_GIFTS => '该赠品已经没有库存,请选择其他赠品',
        self::YOUR_INVENTORY_SHORTAGE => '您的商品库存不足',
        self::ACTIVITIES_IN_THE_MAINTENANCE_PLEASE_TRY_AGAIN_LATER => '活动维护中,请稍后再试',
        self::NUMBER_OF_GIFTS_CAN_NOT_BE_EMPTY => '赠品数量不能空',
        self::COMMODITY_INVENTORY => '商品还有库存',
        self::YOU_DO_NOT_MEET_THE_CONDITIONS_ACTIVITIES_OH => '亲,您不符合活动条件哦',
        self::ACTIVITY_ID_IS_NEED => '缺少活动ID',
        self::ACTIVITY_IS_ON_CANNOT_EDIT => '已上线活动不允许修改',
        self::ACTIVITY_TYPE_ID_ERROR  => '活动类型ID错误',
        self::ACTIVITY_WAREHOUSE_ID_NEED => '缺少活动仓库',
        self::ACTIVITY_TITLE_ID_NEED => '缺少活动标题',
        self::ACTIVITY_BRAND_HAS_IN_ACTIVITY => '品牌已参加活动',
        self::ACTIVITY_GOODS_HAS_IN_ACTIVITY => '商品已参加活动',
        self::ACTIVITY_GOODS_HAS_IN_PRESALE => '商品已参加预售活动',
        self::ACTIVITY_PRESENT_GOODS_PRICE_OR_NUM_CANNOT_EMPTY => '赠品件数或价格不能为空',
        self::ACTIVITY_PRESENT_GOODS_NUM_CANNOT_EMPTY => '赠品数量不能为空',
        self::ACTIVITY_WAREHOUSE_ERROR  => '活动仓库错误',
        self::ACTIVITY_PRESENT_WAREHOUSE_ERROR => '活动赠品仓库错误',
        self::ACTIVITY_BRAND_WAREHOUSE_ERROR  => '活动品牌仓库错误',
        self::ACTIVITY_UPDATE_ERROR  => '活动更新错误',
        self::ACTIVITY_IS_STOP_CANNOT_UPDATE_CACHE => '非开始中活动不能更新缓存',
        self::ACTIVITY_ID_ERROR  => '活动ID错误',
        self::ACTIVITY_GOODS_IS_NEED  => '缺少活动商品',
        self::ACTIVITY_PARAM_IS_NEED  => '缺少活动参数',
        self::ACTIVITY_ADD_ERROR  => '添加活动类型失败',
        self::ACTIVITY_TYPE_NAME_CANNOT_EMPTY => '活动类型名称不能为空',
        self::ACTIVITY_TYPE_ATTRIBUTE_CANNOT_EMPTY => '活动类型描述不能为空',
        self::ACTIVITY_CONDITION_CANNOT_EMPTY  => '活动条件不能为空',
        self::ACTIVITY_WAREHOUSE_CANNOT_EMPTY => '活动仓库不能为空',
        self::ACTIVITY_TYPE_ID_IS_NEED => '缺少活动类型ID',
        self::ACTIVITU_ADDITION_TIMES_BEYOND_LIMIT => '赠品条件叠加次数超过限制',
        self::ACTIVITU_ADDITION_PRESENT_CANNOT_MORE_THAN_ONE => '叠加条件活动赠品不能超过一个',
        self::ACTIVITY_ADDITION_HIGHER_CONDITION_MUST_BE_SET => '叠加条件活动必须限制最大赠送条件',
        self::ACTIVITY_GOODS_CACHE_UPDATE_ERROR => '活动缓存更新失败',
        self::ACTIVITY_PRESENT_GOODS_CAN_NOT_BE_EMPTY => '活动赠品不能为空',
        self::ACTIVITY_CONDITION_CAN_NOT_BE_EMPTY => '活动条件不能为空',
        self::ACTIVITY_CONDITION_ADDITION_CAN_NOT_BE_EMPTY => '赠品叠加次数不能为空',
        self::ACTIVITY_ONLY_WHICHIS_TO_BE_START_CAN_BE_DELETE  => '只有待开始活动能被删除',
        self::ACTIVITY_ONLY_WHICHIS_START_CAN_BE_STOP => '只有进行中活动能关闭',
        self::ACTIVITY_ONLY_WHICHIS_TO_BE_START_CAN_BE_START => '只有待开始活动能开始',
        self::ID_USER_OPERATION_FAILED_ERROR => '操作失败,用户ID错误',
        self::HONGKONG_WAREHOUSE_ORDER_DOES_NOT_SUPPORT_WECHAT_PAYMENT  => '香港仓订单不支持微信支付',
        self::THE_GOODS_IN_YOUR_VICINITY_HAVE_A_BIG_SELLERS_IN_THE_SALEPLEASE_CHOOSE_OTHER_BRAND_DIFFERENCE_MANAGEMENT => '该商品在您的附近已经有个大卖家在销售，建议您选择其他品牌差异化经营。',
        self::SETTLE_EXPRESS_ID_ERROR => '请选择正确快递方式',
        self::SETTLE_EXPRESS_NAME_ERROR => '请选择正确快递方式',
        self::SETTLE_EXPRESS_ERROR => '获取不到快递方式',
        self::SETTLE_GOODS_ERROR => '结算商品错误',
        self::SETTLE_PAY_TYPE_ERROR => '支付类型错误',
        self::SETTLE_GOODS_PRICE_ERROR => '结算商品价格错误',
        self::SETTLE_GOODS_NUM_ERROR => '结算商品价数量错误',
        self::SETTLE_CANNOT_GET_ORDER_GOODS_INFO => '获取不到订单商品信息',
        self::CART_GOODS_ID_ERROR => '购物车商品ID错误',
        self::CART_SALER_ID_ERROR => '购物车用户ID错误',
        self::CART_GOODS_ERROR => '购物车商品错误',
        self::CART_GODDS_WAREHOUSE_ERROR => '购物车商品仓库错误',
        self::CART_PRESENT_GOODS_ID_ERROR => '购物车赠品ID错误',
        self::EXPRESS_GOODS_ERROR => '商品参数错误',
        self::EXPRESS_ID_ERROR => '快递ID错误',
        self::EXPRESS_PAYTYPE_ERROR => '支付类型错误',
        self::ACTIVITY_GOODS_OFF_ID_ERROR => '您的活动ID错误',
        self::ACTIVITY_GOODS_OFF_TITLE_CANNOT_BE_EMPTY => '活动标题不能为空',
        self::ACTIVITY_GOODS_OFF_UNIT_ATTRIBUTE_CANNOT_BE_EMPTY => '活动属性不能为空',
        self::ACTIVITY_GOODS_OFF_CONDITION_CANNOT_BE_EMPTY => '活动条件不能为空',
        self::ACTIVITY_GOODS_CONDITION_IN_GOODS_OFF => '满赠活动商品不能参与满免',
        self::ACTIVITY_GOODS_OFF_CONDITION_MUST_INCREASE => '活动条件必须递增',
        self::ACTIVITY_GOODS_OFF_CART_NUM_ERROR => '活动商品购物车数量错误',
        self::ACTIVITY_GOODS_OFF_CANNOT_IN_MULTI_ACTIVITY => '商品不能重复参与满免活动',
        self::ACTIVITY_GOODS_OFF_BRAND_CANNOT_IN_MULTI_ACTIVITY => '品牌不能重复参与满免活动',
        self::ACTIVITY_GOODS_OFF_GOODS_ID_ERROR => '活动商品ID错误',
        self::ACTIVITY_GOODS_OFF_BRAND_ID_ERROR => '活动品牌ID错误',
        self::ACTIVITY_GOODS_OFF_ONLY_WAITFORSTART_CANNOT_EDIT => '只能编辑待开始活动',
        self::ACTIVITY_GOODS_OFF_UPDATE_ERROR => '更新活动商品错误',
        self::ACTIVITY_GOODS_OFF_ONLY_WHICHIS_TO_BE_START_CAN_BE_DELETE => '只有待开始活动能被删除',
        self::ACTIVITY_GOODS_OFF_ONLY_WHICHIS_START_CAN_BE_STOP => '只有进行中活动能关闭',
        self::ACTIVITY_GOODS_OFF_ONLY_WHICHIS_TO_BE_START_CAN_BE_START => '只有待开始活动能开始',
        self::ADD_CART_NUM_GT_ONE => '添加购物车数量必须大于1',
        self::REFUND_IS_LOCKED => '该退款单已经被系统锁定,请勿操作',
        self::INVOICE_DOES_NOT_EXIST => '发票信息不存在',
        self::FAILED_TO_ADD_INVOICE_REQUEST => '申请发票失败',
        self::DATA_DOES_NOT_EXIST => '获取数据失败',
        self::TOKEN_CHECK_ERROR => 'token验证失败',
        self::YOUR_REQUEST_IS_FORBIDDEN => '请求参数错误',
    );

    /**
     * 老错误码，为了兼容以前的一些错误码，现在不允许在此处新增错误码
     * @var array
     */
    private static $old_errCode =  array(
        '18001' => '未知错误',
        '10000' => '参数错误',
        '10001' => '设备类型错误',
        '10002' => '手机号码错误',
        '10003' => '操作错误',
        '10004' => '请先登录',
        '10005' => '收货地址的省市必须与认证的省市一致',
        '10006' => '您已注册，请直接登录',
        '10007' => '您未注册，请先注册',
        '10008' => '销售员暂不能代客户下单',
        '20001' => '手机号码已被注册',
        '20002' => '手机号码未验证',
        '20003' => '用户不存在',
        '20004' => '密码错误',
        '20005' => '验证码错误',
        '20006' => '地址错误',
        '20007' => '昵称已被注册',
        '20008' => '该手机号码未注册，请先注册',
        '20009' => '您现在不能提交店铺基础资料',
        '20010' => '您现在不能提交店铺完善资料',
        '20011' => '您现在不能修改发票信息',
        '20012' => '初始店铺地址不允许删除',
        '20013' => '您的状态修改不被允许',
        '20014' => '初始店铺地址不允许修改',
        '20015' => '您尚未提交发票信息',
        '20016' => '缺少用户ID',
        self::OPTION_FAILED => '操作失败',
        '30001' => '货物已发出，取消失败',
        '30002' => '不能取消别人的订单',
        '30003' => '该订单已取消，不要重复操作',
        '30004' => '退款失败，请联系客服',
        '30005' => '订单取消失败，请联系客服',
        '30006' => '订单正在取消中，请稍等',
        '30007' => '不能删除他人订单',
        '30008' => '该订单已删除，不要重复操作',
        '30009' => '当前订单不能删除',
        '30010' => '订单删除失败',
        '30011' => '订单已经发货，不能取消订单或者退款',
        '30012' => '订单未支付，不能操作退款',
        '30013' => '缺少订单ID',
        '30014' => '不能取消他人订单',
        '30015' => '该订单已取消，不要重复操作',
        '30016' => '订单取消失败',
        '30017' => '仓库不允许订单修改',
        '30018' => '仓库订单修改失败',
        '30019' => '订单修改失败',
        '30020' => '请输入正确优惠金额',
        '30021' => '获取不到订单详情',
        '30022' => '订单已经支付',
        '30023' => '订单价格低于优惠金额',
        '30024' => '订单商品错误',
        '30025' => '订单运费错误',
        '30026' => '订单还未支付,请让客户重新下单',
        '30027' => '订单包含优惠券,不能改单',
        '30028' => '订单参与满赠活动,不能改单',
        '30029' => '订单参与预售活动,不能改单',
        '30030' => '该商品不存在或者已经下架',
        '30031' => '订单商品价格错误',
        '30032' => '非赠品商品价格不能为0',
        '30033' => '缺少收货人手机号',
        '30034' => '获取不到下单人用户信息',
        '30035' => '缺少收货人地址信息',
        '30036' => '收货地址错误',
        '30037' => '缺少支付类型',
        '30038' => '订单用户信息错误',
        '30039' => '订单商品数量错误',
        '30040' => '请输入合法的订单ID',
        '30041' => '请输入线下支付金额',
        '30042' => '您没有线下支付确认权限',
        '30043' => '请出入线下支付支付类型',
        '30044' => '订单线下支付状态修改失败',
        '30045' => '订单详情参数必须为数组',
        '30046' => '订单数据为空',
        '30047' => '订单已支付,不能再次添加流水',
        '30048' => '订单修改参数为空',
        '30049' => '订单未选择支付类型',
        '30050' => '订单商品数量不能为0',
        '30051' => '获取运费信息失败',
        '30052' => '您提交的参数错误',
        '30053' => '您的请求不被允许',
        '30054' => '获取订单状态错误',
        '30055' => '订单发票类型错误',
        '30056' => '获取不到订单收货地址',
        '30057' => '订单商品仓库错误',
        '40001' => '暂时没有可支付订单',
        '50001' => '文件上传失败',
        '50002' => '您未提交任何内容',
        '50003' => '请您使用正确方式上传',
        '50004' => '文件上传失败,请重新尝试',
        '50005' => '非允许文件上传格式',
        '50006' => '文件大小超出限制,请上传不超过5M的图片',
        '60000' => '获取商品数据失败',
        '60001' => '非允许购买数量',
        '60002' => '商品库存不足',
        self::ORDER_PRE_PRICE_NOT_GREATER_THAN_GOODS_TOTAL_PRICE => '优惠价格不能大于商品总价',
        '60003' => '非允许购买数量',
        '60004' => '非允许购买数量',
        '60005' => '非允许购买数量',
        '60006' => '订单金额不满足购买条件',
        '60007' => '非允许销售地区',
        '60008' => '获取商品数据失败',
        '60009' => '获取商品数据失败',
        '600010' => '获取商品数据失败',
        '600011' => '获取商品数据失败',
        '600012' => '获取商品数据失败',
        '600013' => '获取商品数据失败',
        '60014' => '赠品不允许购买',
        '60015' => '超过限购数量',
        '70001' => '商品不存在',
        '70002'=>  '需要支付的金额为0，不需要再支付',
        '70003'=>  '订单金额已经超过30万，请联系客服线下转账',
        '80001' => '订单异常',
        '80002' =>  '没达到预收批次最低起批价',
        '80003' => '获取取消订单数据失败',
        '90001' => '请先实名认证',
        '11001' => '退换商品数量不能大于订单商品数量',
        '11002' => '您已经提交过申请,请勿重复提交',
        '11003' => '异常退换货申请',
        '11004' => '请填写详细原因',
        '11005' => '请先确认收货',
        '11006' => '已经超过无理由退换货时间',
        '11007' => '您的订单还未签收，请确认已收到货物',
        '11008' => '您的申请还未通过审核',
        '11009' => '您已经提交过申请',
        '99999' => '系统升级维护中,请稍后再试！',
        '12000' => '您的版本已过期，请升级最新版本',
        '13000' => '优惠劵领取失败',
        '13001' => '获取优惠劵失败',
        '13002' => '兑换码可以使用',
        '13003' => '兑换码已失效',
        '13004' => '找不到对应的优惠劵，请核实后重新输入',
        '13005' => '优惠劵格式不正确，请重试',
        '13006' => '兑换码已被使用',
        '13007' => '暂无优惠劵',
        '13008' => '请先登录！',
        '13009' => '劵已被领完',
        '13010' => '已领取，不能重复领取',
        '13015' => '该类优惠劵一个用户只能领取和使用一次',
        '13011' => '优惠劵不可用',
        '13012' => '此订单未发货，不能确认收货哦',
        '14000' => '满赠活动信息错误',
        '14001' => '您的活动参数有误',
        '14002' => '您的活动参数无效',
        '14003' => '您的用户参数无效',
        '14004' => '无法获取活动信息',
        '14005' => '您的商品参数无效',
        '14006' => '您还未满足赠品领取条件',
        '14007' => '找不到活动商品',
        '14008' => '找不到活动赠品',
        '14009' => '您已经领取过该活动赠品',
        '14010' => '该赠品已经没有库存,请选择其他赠品',
        '14011' => '您的商品库存不足',
        '14012' => '活动维护中,请稍后再试',
        '14013' => '赠品数量不能空',
        '14014' => '商品还有库存',
        '14015' => '亲,您不符合活动条件哦',
        '14016' => '缺少活动ID',
        '14017' => '已上线活动不允许修改',
        '14018' => '活动类型ID错误',
        '14019' => '缺少活动仓库',
        '14020' => '缺少活动标题',
        '14021' => '品牌已参加活动',
        '14022' => '商品已参加活动',
        '14023' => '商品已参加预售活动',
        '14024' => '赠品件数或价格不能为空',
        '14025' => '赠品数量不能为空',
        '14026' => '活动仓库错误',
        '14027' => '活动赠品仓库错误',
        '14028' => '活动品牌仓库错误',
        '14029' => '活动更新错误',
        '14030' => '非开始中活动不能更新缓存',
        '14031' => '活动ID错误',
        '14032' => '缺少活动商品',
        '14033' => '缺少活动参数',
        '14034' => '添加活动类型失败',
        '14035' => '活动类型名称不能为空',
        '14036' => '活动类型描述不能为空',
        '14037' => '活动条件不能为空',
        '14038' => '活动仓库不能为空',
        '14039' => '缺少活动类型ID',
        '14040' => '赠品条件叠加次数超过限制',
        '14041' => '叠加条件活动赠品不能超过一个',
        '14042' => '叠加条件活动必须限制最大赠送条件',
        '14043' => '活动缓存更新失败',
        '14044' => '活动赠品不能为空',
        '14045' => '活动条件不能为空',
        '14046' => '赠品叠加次数不能为空',
        '14047' => '只有待开始活动能被删除',
        '14048' => '只有进行中活动能关闭',
        '14049' => '只有待开始活动能开始',
        '15001' => '操作失败,用户ID错误',
        '16001' => '香港仓订单不支持微信支付',
        '17001' => '该商品在您的附近已经有个大卖家在销售，建议您选择其他品牌差异化经营。',
        '19001' => '请选择正确快递方式',
        '19002' => '请选择正确快递方式',
        '19003' => '获取不到快递方式',
        '19004' => '结算商品错误',
        '19005' => '支付类型错误',
        '19006' => '结算商品价格错误',
        '19007' => '结算商品价数量错误',
        '19008' => '获取不到订单商品信息',
        '21001' => '购物车商品ID错误',
        '21002' => '购物车用户ID错误',
        '21003' => '购物车商品错误',
        '21004' => '购物车商品仓库错误',
        '21005' => '购物车赠品ID错误',
        '22001' => '商品参数错误',
        '22002' => '快递ID错误',
        '22003' => '支付类型错误',
        '24001' => '您的活动ID错误',
        '24002' => '活动标题不能为空',
        '24003' => '活动属性不能为空',
        '24004' => '活动条件不能为空',
        '24005' => '满赠活动商品不能参与满免',
        '24006' => '活动条件必须递增',
        '24007' => '活动商品购物车数量错误',
        '24008' => '商品不能重复参与满免活动',
        '24009' => '品牌不能重复参与满免活动',
        '24010' => '活动商品ID错误',
        '24011' => '活动品牌ID错误',
        '24012' => '只能编辑待开始活动',
        '24013' => '更新活动商品错误',
        '24014' => '只有待开始活动能被删除',
        '24015' => '只有进行中活动能关闭',
        '24016' => '只有待开始活动能开始',
        '39001' => '添加购物车数量必须大于1',
        self::REFUND_IS_LOCKED => '该退款单已经被系统锁定,请勿操作'
    );

    /**
     * 合并错误代码
     */
    public static function mergeErrCode($errCode){
        foreach ($errCode as $k => $v) {
            self::$errCode[$k] = $v;
        }
        //将新老错误码合并
        $config_array = self::$errCode+self::$old_errCode;
        return $config_array;
    }
    public static function getErrMsg($err=0){
        if($err){
            return self::$errCode[$err]?self::$errCode[$err]:self::$errCode[18001];
        }
        return self::$errCode[18001];
    }
}